### ISSUE TITLE
Saved files have keys jumbled around, should be same order or sorted

### ISSUE THREAD

**Issue by odinns** [Laravel-Backpack/langfilemanager#29]
It is very annoying that the language strings are shown in jumbled / random order in the webinterface and also saved in jumbled order. They should optimally keep the order they were found in the file or be sorted alphabetically by key.

**Comment by tabacitu** [comment]
@oad-dwarf , totally agree. In the upcoming version of LangFileManager, the actual langfiles won't be modified anymore. A second layer will be introduced - a database layer - in the form of a "translation_files" table where we store everything in the lang files. ```lang('file.string')``` will pull the translation from the database and will only resort to the translation file if the string doesn't exist in the database.

This will solve both the jumbled order and the formatting problems, because the actual .php files won't be modified anymore, they'll only be used to "restore" one/more translation strings to their original value.

What do you think about this solution?

**Comment by dummand** [comment]
Maybe just remove the asort in 'getFileContent' in LangFiles.php?

**Comment by lloy0076** [comment]
The solution sounds reasonable but it's essentially a won't fix on this version.
