### ISSUE TITLE
Change from file storage to database storage

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/langfilemanager#3]
Modifying lang files causes git conflicts in production. Which are A PAIN IN THE ASS to fix, since most of the times you have to do it in VIM.

What I think we should do is:
- when want to edit a file, parse the file; add all new keys in the database;
- when you edit a key, we only update it in the database, not in the lang file;
- at boot(), we fetch the values for the current language from the database and use those, just like we do in the SettingsManager package;

This will also allow us to create a new feature: if someone fucks up a langfile translation, we can "restore default values" by fetching them from the file.

**Comment by tabacitu** [comment]
Another obvious benefit would be that then we could use a Dick/CRUD interface to manage them. So you would have the ability to search.

That's a more intuitive way to change something, from a noob user perspective:
- go to the language section
- search for your string
- find it and update it
- done

**Comment by tabacitu** [comment]
Fortunately, spatie has launched this package ([github](https://github.com/spatie/laravel-translation-loader/), [blog](https://murze.be/2016/10/laravel-package-store-language-lines-database/)).

All we need is to create a CRUD for it :-)

**Comment by tabacitu** [comment]
But i think it stores all translations in a JSON inside the `text` column, which is not ideal. On MySQLs without JSON columns search would be pretty slow... I think a `lang` or `locale` column in the table would be better. 

Food for thought...

**Comment by ablunier** [comment]
Could this be a more appropriate package to leverage on the storage of the translations according to the design that you are looking for? https://github.com/Waavi/translation

**Comment by tabacitu** [comment]
@ablunier yes, it looks perfect, thank you. We might just need to create a CRUD panel for the table this package needs :-)

**Comment by ablunier** [comment]
Let me know if you want me to help!

**Comment by lloy0076** [comment]
@ablunier [Waavi's package](https://github.com/Waavi/translation) certainly looks good.

@tabacitu - is this still a relevant issue?

**Comment by promatik** [comment]
Hey everyone!

I'm happy to announce that we just released a new package [Translation Manager](https://github.com/Laravel-Backpack/translation-manager). This new package uses [Spatie Translation Loader](https://github.com/spatie/laravel-translation-loader) under the hood and will eventually replace LangFileManager, since it works in a more predictable way, using the database to store translations.

I'll close this one for now, let's move our focus and efforts into improving Translation Manager 💪.

---

Side note, the main purpose of Translation Manager is to solve exactly this issue 🎉
