### ISSUE TITLE
Fire event after file save

### ISSUE THREAD

**Issue by dobromir-hristov** [Laravel-Backpack/langfilemanager#40]
I checked before I asked, but still.. Is there a way to run scripts after the lang files are saved? For example to generate a json file with the translation strings.

In our case, we use `Vue` and `laravel-vue-i18n-generator` to pass the translations to the frontend.

**Comment by tabacitu** [comment]
Hmm... There's no "hook" or anything, but you can extend the package and use your own controller instead of LanguageCrudController, then overwrite [the updateTexts() method](https://github.com/Laravel-Backpack/LangFileManager/blob/master/src/app/Http/Controllers/LanguageCrudController.php#L133-L162) to do that too.

Hope it helps.

**Comment by dobromir-hristov** [comment]
Ye, already did that. Thanks.
